name: pr

on:
  pull_request:
    branches:
      - master 

permissions:
  pull-requests: write

jobs:

  check-version:
    runs-on: ubuntu-latest

    steps:

      - name: Check-version
        uses: o0th/action-check-version@v0.0.6
