name: testing

on:
  push:
    branches:
      - master 

permissions:
  contents: write

jobs:

  testing:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: ./
        with:
          file: testing.md
          vars: |
            {{name}} = World!
